#!/usr/bin/env python3
"""Generate the routine sandbox's setup.sh (and optional restore script).

setup.sh runs FIRST when the Anthropic routine sandbox boots, before Claude
Code starts. The sandbox is fresh Linux with only language runtimes and
package managers; setup.sh is the window to install CLIs and stage MCP config
before Claude takes over.

IMPORTANT - credential restore must NOT happen in setup.sh. The routine's
"Environment variables" are injected into the Claude Code AGENT session, NOT
into the pre-launch setup script. A setup.sh that does
`printf "$MY_SECRET" > creds` silently writes nothing (it hits the empty-var
branch, still exits 0, shows "Ran setup script - Completed") and the agent then
finds no credential. So credential restore is emitted to a SEPARATE script that
runs INSIDE the agent session via a SessionStart hook (wired by scaffold_repo.sh
into .claude/settings.json). Pass --restore-out to split it out.

The script body is built by concatenating each matched connector's
routine-install.sh content (install phase) and, separately, each matched
connector's routine-restore.sh content (restore phase). Shebangs on inlined
connector scripts are stripped.

Unmatched CLIs and unknown MCPs become `# TODO` comments in the install phase.

Usage:
    python3 generate_setup_sh.py <resolution.json> [--restore-out <file>]

Without --restore-out, the restore phase is appended to setup.sh (legacy, for
back-compat). With --restore-out, setup.sh is install-only and the restore
phase is written to <file> as a standalone agent-context script.
"""
import argparse
import json
import sys
from pathlib import Path


def stripShebang(scriptText):
    lines = scriptText.splitlines(keepends=True)
    if lines and lines[0].startswith("#!"):
        return "".join(lines[1:])
    return scriptText


def readRoutineScript(connectorPath, scriptName):
    path = Path(connectorPath) / scriptName
    if not path.is_file():
        return None
    return stripShebang(path.read_text(encoding="utf-8"))


def buildInstallParts(resolution):
    parts = []
    # Install phase: routine-install.sh content for every matched connector
    for c in resolution.get("matched_connectors", []):
        depName = c["dep_name"]
        installScript = readRoutineScript(c["connector_path"], "routine-install.sh")
        if installScript is None:
            parts.append(f"# TODO: {depName} connector lacks routine-install.sh (path: {c['connector_path']})")
            parts.append(f"# Add a routine-install.sh for the '{depName}' connector before using this routine.")
            parts.append("")
            continue
        parts.append(f"# === install: {depName} ===")
        parts.append(installScript.rstrip())
        parts.append("")

    # TODO comments for unmatched CLIs
    for cli in resolution.get("unmatched_clis", []):
        parts.append(f"# TODO: unmatched CLI '{cli}' - no connector resolved for it.")
        parts.append(f"#       Add a connector for '{cli}' (copy an existing connector folder and edit),")
        parts.append(f"#       OR install {cli} inline below.")
        parts.append("")

    # TODO comments for unknown MCPs
    for mcp in resolution.get("unknown_mcps", []):
        parts.append(f"# TODO: MCP server '{mcp}' referenced by the skill but not present in ~/.claude.json on this laptop.")
        parts.append("#       Plugin cannot infer config; add the server config manually to .mcp.json.")
        parts.append("")

    return parts


def buildRestoreParts(resolution):
    parts = []
    for c in resolution.get("matched_connectors", []):
        depName = c["dep_name"]
        restoreScript = readRoutineScript(c["connector_path"], "routine-restore.sh")
        if restoreScript is None:
            parts.append(f"# TODO: {depName} connector lacks routine-restore.sh (path: {c['connector_path']})")
            parts.append("")
            continue
        parts.append(f"# === restore: {depName} ===")
        parts.append(restoreScript.rstrip())
        parts.append("")
    return parts


def generateSetupSh(resolution, splitRestore=False):
    skillName = resolution.get("skill_name", "skill")
    parts = []
    parts.append("#!/usr/bin/env bash")
    parts.append(f"# setup.sh for routine packaging {skillName}")
    parts.append("# Auto-generated by routine-installer-plugin.")
    parts.append("# Runs in a fresh Anthropic routine sandbox before Claude Code starts.")
    parts.append("set -e")
    parts.append("")
    parts.append('echo "[setup.sh] boot - installing CLIs"')
    parts.append("")

    parts.extend(buildInstallParts(resolution))

    if splitRestore:
        parts.append('echo "[setup.sh] CLIs installed - credential restore runs at agent start (SessionStart hook)"')
    else:
        parts.append('echo "[setup.sh] CLIs installed - restoring credentials"')
        parts.append("")
        parts.extend(buildRestoreParts(resolution))

    parts.append('echo "[setup.sh] done - Claude Code launching"')

    return "\n".join(parts) + "\n"


def generateRestoreSh(resolution):
    skillName = resolution.get("skill_name", "skill")
    parts = []
    parts.append("#!/usr/bin/env bash")
    parts.append(f"# restore-credentials.sh for routine packaging {skillName}")
    parts.append("# Auto-generated by routine-installer-plugin.")
    parts.append("# Runs via a SessionStart hook (.claude/settings.json) INSIDE the Claude Code")
    parts.append("# agent session - that context has the routine's secret env vars; the pre-launch")
    parts.append("# setup.sh does NOT. References env var NAMES only; contains no secret values.")
    parts.append("set +e")
    parts.append("")
    parts.append('echo "[restore-credentials] restoring credentials"')
    parts.append("")

    restoreParts = buildRestoreParts(resolution)
    if restoreParts:
        parts.extend(restoreParts)
    else:
        parts.append("# No connector credentials to restore for this skill.")
        parts.append("# If a ladder-resolved dependency needs a credential decoded from an env")
        parts.append("# var (e.g. base64 -> a config file), add the decode command(s) here.")
        parts.append("")

    parts.append('echo "[restore-credentials] done"')

    return "\n".join(parts) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("resolution", help="Resolution JSON from map_deps_to_connectors.py")
    parser.add_argument(
        "--restore-out",
        default=None,
        help="Write the credential-restore phase to this file as a standalone "
        "agent-context script (SessionStart hook). setup.sh becomes install-only.",
    )
    parser.add_argument(
        "--setup-out",
        default=None,
        help="Write setup.sh to this file instead of stdout. Prefer this over a "
        "shell redirect: a `> setup.sh 2>&1` would capture this script's stderr "
        "diagnostics into setup.sh as stray lines.",
    )
    args = parser.parse_args()

    try:
        with open(args.resolution) as f:
            resolution = json.load(f)
    except FileNotFoundError:
        print(f"generate_setup_sh: resolution not found: {args.resolution}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"generate_setup_sh: invalid JSON ({e})", file=sys.stderr)
        sys.exit(1)

    splitRestore = args.restore_out is not None
    setupText = generateSetupSh(resolution, splitRestore=splitRestore)
    if args.setup_out:
        Path(args.setup_out).write_text(setupText, encoding="utf-8")
        print(f"generate_setup_sh: wrote setup.sh to {args.setup_out}", file=sys.stderr)
    else:
        sys.stdout.write(setupText)

    if splitRestore:
        Path(args.restore_out).write_text(generateRestoreSh(resolution), encoding="utf-8")
        print(f"generate_setup_sh: wrote restore script to {args.restore_out}", file=sys.stderr)


if __name__ == "__main__":
    main()
